CREATE TABLE IF NOT EXISTS books(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,link TEXT NOT NULL UNIQUE,author TEXT DEFAULT '',updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);
CREATE TABLE IF NOT EXISTS users(user_id INTEGER PRIMARY KEY,username TEXT DEFAULT '',full_name TEXT DEFAULT '',started_at INTEGER NOT NULL);